account/urls.py
from django.urls import path,re_path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'project'

urlpatterns=[
    path('', views.social_view, name='social_view'),
    path('projects/', views.project_view, name='project_view'),
    path('register/user_register', views.user_register, name='user_register'),
    path('login/user_login', views.user_login, name='user_login'),
    path('register/dashboard/', views.dashboard, name='dashboard'),
    path('login/dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot_password/user_forgot_password', views.forgot_password, name='user_forgot_password'),
    path('password_reset/done', views.password_reset_done, name='password_reset_done'),
        path('chatlogin/', views.chatlogin, name='chatlogin'),
]

website/urls.py
from django.contrib import admin
from django.urls import path,include
from chat import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace='project')),
    path('chat/', views.index,name='chat'),
     path('chat/<str:username>', views.chat,name='chatmessage'),
    path('addcustomer/<str:name>',views.addcustomer,name="addcustomer"),
     path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
        path('api/messages', views.message_list, name='message-list'),
]

templates/project/post/dashboard.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>

    <link rel="stylesheet" href=" {% static 'css/chat.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
</head>
<body>
  <div class="sidebar">
    <div class="logo-details">
      <i class='bx bxl-c-plus-plus'></i>
      <a href="{% url 'project:social_view' %}" class="logo_name">GBTECH</a>
    </div>
      <ul class="nav-links">
        <li>
          <a href="#" class="active">
            <i class='bx bx-grid-alt' ></i>
            <span class="links_name">Dashboard</span>
            <span>{{ request.get_user.username }}</span>
          </a>
        </li>
      </ul>
  </div>
  <section class="home-section">
    <nav>
      <div class="sidebar-button">
        <i class='bx bx-menu sidebarBtn'></i>
        <span class="dashboard">Dashboard</span>
      </div>
    </nav>

    <div class="home-content">
      <div class="overview-boxes">
        <div class="box">
          <div class="right-side">
            <div class="box-topic">Completed Projects</div>
            <div class="number">2</div>
          </div>
          <!-- <i class='bx bx-cart-alt cart'></i> -->
          <i class="fa-solid fa-trophy"></i>
        </div>
        <div class="box">
          <div class="right-side">
            <div class="box-topic">Payments</div>
          </div>
          <!-- <i class='bx bxs-cart-add cart two' ></i> -->
          <i class="fa-solid fa-credit-card"></i>
        </div>
        <div class="box">
          <div class="right-side">
            <div class="box-topic">Transaction History</div>
          </div>
          <i class='bx bx-cart cart three' ></i>
        </div>
      </div>

  <div class="chat-collapse">
    <button id="chat-btn" type="button" class="collapse">chat with us
        <i id="chat-icon" style="color: white;" class="fa fa-fw fa-comments-o"></i>
    </button>
    <div class="content">
        <div class="full-chat-block">
        <div class="outer-contain">
            <div class="chat-container">
                <div id="chat-box">
                    <h5 id="chat-time"></h5>
                    <p id="chat-msg" class="chat-bot"><span>...loading</span></p>
                </div>
                <div class="chat-input-content">
                    <div id="chat-input">
                        <input type="text" name="msg" id="textinput" class="input-box" placeholder="tap to send a message">
                        <p ></p>

                    </div>
                    <div class="chat-btn-icon">
                        <i id="chat-icon" style="color: crimson;" class="fa fa-fw fa-heart" onclick="heartButton()"></i>
                        <i id="chat-icon" style="color: #333;" class="fa fa-fw fa-send" onclick="sendButton()"></i>                        
                    </div>
                </div>
                <div id="chat-bar-bottom">
                    <p></p>
                </div>
            </div>
            
        </div>

    </div>
  </div>
</div>
  
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{% static 'chat.js' %}"></script>
<script>
  let sidebar = document.querySelector(".sidebar");
  let sidebarBtn = document.querySelector(".sidebarBtn");
  sidebarBtn.onclick = function() {
    sidebar.classList.toggle("active");
    if(sidebar.classList.contains("active")){
    sidebarBtn.classList.replace("bx-menu" ,"bx-menu-alt-right");
  }else
    sidebarBtn.classList.replace("bx-menu-alt-right", "bx-menu");
  }
</script>
</body>
</html>

templates/project/post/forgot_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title Page-->
	<title>Login Page</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    
    <div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins" style="background: #00203fff;">
        <div class="wrapper wrapper--w780">
            <div class="card card-3">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title">Login</h2>
                            <form method="post" action="user_forgot_password" id="form">
                                {% csrf_token %}
                                        <div class="input-group">
                                            <input class="input--style-3" id='email' type="email" placeholder="Input your Email" name="email" required="">
                                        </div>
                                <div class="p-t-10">
                                    <button class="btn btn--pill btn--green" id='submit' type="submit">Submit</button>
                                </div>
                                <p class="mt-3" style="color: #fff;"><a href="{% url 'project:user_login' %}">Return to Login Page</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>


</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

templates/project/post/home.html
{% extends "project/base.html" %}
{% load static %}
{% block title %} Home Page {% endblock %}

{% block content %}
    </section>
    <!-- Portfolio-->

    <section id="portfolio" class="content-section">
        <div class="container">
            <div class="content-section-heading text-center">
                <h3 class="text-secondary mb-0">Portfolio</h3>
                <h2 class="mb-5">Projects</h2>
            </div>
            <div class="project-wrapper">
               <div class="row mb-3"> 
                <div class="col-lg-4 col-sm-12"> 
               <div class="load-hidden project-wrapper__text mb-2" style="visibility: visible;">
                    <h3 class="project-wrapper__text-title">Exam System</h3> 
                    <div> 
                       <p class="mb-4">A Monitoring System website that is used to take Exams. </p> 
                   </div>
                    <a rel="noreferrer" target="_blank" class="cta-btn cta-btn--hero" href="http://exam-monitor.mjobi.com/"> See Live </a> 
                    <a rel="noreferrer" target="_blank" class="cta-btn text-color-main" href="https://github.com/GokeAdewuyi/CAMS"> Source Code </a>
                    </div>
               </div> 
               <div class="col-lg-8 col-sm-12"> 
                   <div class="load-hidden project-wrapper__image mb-2" style="visibility: visible;">
                        <a rel="noreferrer" href="https://exam-monitor.mjobi.com/" target="_blank">
                           <div data-tilt="" data-tilt-max="4" data-tilt-glare="true" data-tilt-max-glare="0.5" class="js-tilt rounded thumbnail" style="transform: perspective(1000px) rotateX(0deg) rotateY(0deg) scale3d(1, 1, 1);">
                               <img alt="Project Image" class="img-fluid" src="{% static 'images/sillos.png' %}"> 
       <div class="js-tilt-glare" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; overflow: hidden; pointer-events: none;">
           <div class="js-tilt-glare-inner" style="position: absolute; top: 50%; left: 50%; pointer-events: none; background-image: linear-gradient(0deg, rgba(255, 255, 255, 0) 0%, rgb(255, 255, 255) 100%); transform: rotate(180deg) translate(-50%, -50%); transform-origin: 0% 0%; opacity: 0; width: 1342px; height: 1342px;">
           </div>
       </div>
   </div>
           </a>
           </div>
        </div> 
       </div> 
       <div class="row mb-3"> 
           <div class="col-lg-4 col-sm-12"> 
               <div class="load-hidden project-wrapper__text mb-2" style="visibility: visible;"> 
                   <h3 class="project-wrapper__text-title">EssLasu Voting system</h3> 
                   <div> 
                       <p class="mb-4">This is a voting System designed for Lagos State University (LASU).</p> 
                   </div>
                   <a rel="noreferrer" target="_blank" class="cta-btn cta-btn--hero" href="http://esslasu.herokuapp.com/"> See Live </a> 
                   <a rel="noreferrer" target="_blank" class="cta-btn text-color-main" href="https://github.com/abiola814/voting-system"> Source Code </a>
               </div> 
           </div> 
           <div class="col-lg-8 col-sm-12"> 
               <div class="load-hidden project-wrapper__image mb-2" style="visibility: visible;"> 
                   <a rel="noreferrer" href="http://esslasu.herokuapp.com/" target="_blank"> 
                       <div data-tilt="" data-tilt-max="4" data-tilt-glare="true" data-tilt-max-glare="0.5" class="js-tilt rounded thumbnail" style="transform: perspective(1000px) rotateX(0deg) rotateY(0deg) scale3d(1, 1, 1);"> 
                           <img alt="Project Image" class="img-fluid" src="{% static 'images/voting-system.png' %}"> 
                           <div class="js-tilt-glare" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; overflow: hidden; pointer-events: none;">
                               <div class="js-tilt-glare-inner" style="position: absolute; top: 50%; left: 50%; pointer-events: none; background-image: linear-gradient(0deg, rgba(255, 255, 255, 0) 0%, rgb(255, 255, 255) 100%); transform: rotate(180deg) translate(-50%, -50%); transform-origin: 0% 0%; opacity: 0; width: 1342px; height: 1342px;">
                               </div>
                           </div>
                       </div>
                    </a> 
                   </div> 
               </div> 
           </div> 
           <div class="row mb-3"> 
               <div class="col-lg-4 col-sm-12"> 
                   <div class="load-hidden project-wrapper__text mb-2" style="visibility: visible;"> 
                       <h3 class="project-wrapper__text-title">Online school Website</h3> 
                       <div> 
                           <p class="mb-4">An online learning website for course management and Exam system. It also consist of article editor</p> 
                       </div> 
                       <a rel="noreferrer" target="_blank" class="cta-btn cta-btn--hero" href="https://e-learning.mjobi.com/"> See Live </a> 
                       <a rel="noreferrer" target="_blank" class="cta-btn text-color-main" href="https://github.com/abiola814/online-learning-system-with-python"> Source Code </a>
                   </div> 
               </div> 
               <div class="col-lg-8 col-sm-12"> 
                   <div class="load-hidden project-wrapper__image" style="visibility: visible;"> 
                       <a rel="noreferrer" href="https://e-learning.mjobi.com/" target="_blank"> 
                           <div data-tilt="" data-tilt-max="4" data-tilt-glare="true" data-tilt-max-glare="0.5" class="js-tilt rounded thumbnail" style="transform: perspective(1000px) rotateX(0deg) rotateY(0deg) scale3d(1, 1, 1);"> 
                               <img alt="Project Image" class="img-fluid" src="{% static 'images/online.jpeg' %}"> 
                               <div class="js-tilt-glare" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; overflow: hidden; pointer-events: none;">
                                   <div class="js-tilt-glare-inner" style="position: absolute; top: 50%; left: 50%; pointer-events: none; background-image: linear-gradient(0deg, rgba(255, 255, 255, 0) 0%, rgb(255, 255, 255) 100%); transform: rotate(180deg) translate(-50%, -50%); transform-origin: 0% 0%; opacity: 0; width: 1342px; height: 1342px;">
                                   </div>
                               </div>
                           </div> 
                       </a> 
                   </div> 
               </div> 
           </div> 
           <div class="row mb-3"> 
               <div class="col-lg-4 col-sm-12"> 
                   <div class="load-hidden project-wrapper__text mb-2" style="visibility: visible;"> 
                       <h3 class="project-wrapper__text-title mb-2">parcel carier</h3>
                       <div> <p class="mb-4">this is a carier system with realtime tracking of driver by using gprs location and google map.</p> 
                       </div> 
                       <a rel="noreferrer" target="_blank" class="cta-btn cta-btn--hero" href="https://delivery.mjobi.com/"> See Live </a> 
                    
                   </div> 
               </div> 
               <div class="col-lg-8 col-sm-12"> 
                   <div class="load-hidden project-wrapper__image mb-2" style="visibility: visible;"> 
                       <a rel="noreferrer" href="https://delivery.mjobi.com/" target="_blank"> 
                           <div data-tilt="" data-tilt-max="4" data-tilt-glare="true" data-tilt-max-glare="0.5" class="js-tilt rounded thumbnail" style="transform: perspective(1000px) rotateX(0deg) rotateY(0deg) scale3d(1, 1, 1); will-change: transform; transition: all 300ms cubic-bezier(0.03, 0.98, 0.52, 0.99) 0s;"> 
                               <img alt="Project Image" class="img-fluid" src="{% static 'images/delivery.png' %}"> 
                               <div class="js-tilt-glare" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; overflow: hidden; pointer-events: none;">
                                   <div class="js-tilt-glare-inner" style="position: absolute; top: 50%; left: 50%; pointer-events: none; background-image: linear-gradient(0deg, rgba(255, 255, 255, 0) 0%, rgb(255, 255, 255) 100%); transform: rotate(180deg) translate(-50%, -50%); transform-origin: 0% 0%; opacity: 0; width: 1342px; height: 1342px; transition: opacity 300ms cubic-bezier(0.03, 0.98, 0.52, 0.99) 0s;">
                                   </div>
                               </div>
                           </div> 
                       </a> 
                   </div> 
               </div> 
           </div> 
       </div>
       <div> 
        <p style="font-size: 22px; float: right;"><a rel="noreferrer" class="cta-btn text-color-main" href="{% url 'project:project_view' %}">See More</a></p>
       </section>  
       <section id="contact" class="bg-primary pt-4 pb-4"> 
           <div class="container"> <h2 class="load-hidden section-title text-center mb-3" style="visibility: visible; color: #fff;">Meet The Developer</h2> 
               <div class="about-wrapper row"> <div class="col-md-6 col-sm-12"> 
                   <div class="about-wrapper__image load-hidden" style="visibility: visible;"> 
                       <img alt="Profile Image" class="img-fluid rounded shadow-lg" height="auto" width="300px" src="https://github.com/abiola814/keylogger/blob/main/44c01feb-bd1f-4f88-abde-28047ef52a9c.jpeg?raw=true"> 
                   </div> 
                </div> 
                <div class="col-md-6 col-sm-12 mb-2 mt-2"> 
                    <div class="about-wrapper__info load-hidden mb-2" style="visibility: visible; color: #fff;"> 
                       <p class="about-wrapper__info-text">I am <strong>Abiola Oladunjoye</strong>I am a goal-oriented software engineer. My favourite language is Python, using Django REST framework for API development and Web Development, using ROS for Robotic development, and I am also comfortable with React JS for mobile Development and Blockchain development. </p> 
                       <div class="d-flex">
                           <span class="d-flex mt-3"> <a rel="noreferrer" target="_blank" class="cta-btn cta-btn--resume" href="https://www.linkedin.com/in/abiola-oladunjoye-8b61351a7/"><i class="fa-brands fa-linkedin-in" style="color:#fff; font-size: larger;"></i></a> </span> 
                           <span class="d-flex mt-3"> <a rel="noreferrer" target="_blank" class="cta-btn cta-btn--resume" href="https://twitter.com/Oladunj90244823"><i class="icon-social-twitter" style="color:#fff; font-size: larger;"></i></a> </span> 
                           <span class="d-flex mt-3"> <a rel="noreferrer" target="_blank" class="cta-btn cta-btn--resume" href="https://github.com/abiola814"><i class="fa-brands fa-github" style="color:#fff; font-size: larger;"></i></a> </span> 
                       </div>
                    </div> 
                   </div> 
               </div> 

                 
           </div> 
       </section> 
{% endblock %}

templates/project/post/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
	<title>Login Page</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    
    <div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins" style="background: #00203fff;">
        <div class="wrapper wrapper--w780">
            <div class="card card-3" style="background: #fff;">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title">Login</h2>
                            <form method="post" action="user_login" id="form">
                                {% csrf_token %}
                                        <div class="input-group">
                                            <input class="input--style-3" id = 'username' type="text" placeholder="Username" name="username" required="">
                                        </div>
                                        <div class="input-group">
                                            <input class="input--style-3" id='password' type="password" placeholder="Password" name="pswd" required="">
                                        </div>
                                <div class="p-t-10">
                                    <button class="btn btn--pill btn--green" id='submit' type="submit">Submit</button>
                                </div>
                                <p class="mt-3" style="color: #00203fff;">Don't have an accout? <a href="{% url 'project:user_register' %}">Register</a></p>
                            </form>
                            <p style="width: 100%; text-align: center;"><a style="color: #00203fff; text-decoration: none;" href="{% url 'project:user_forgot_password' %}">Forgot Password?</a></p>
                        </div>
                    </div>
                </div>
            </div>

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

templates/project/post/password_reset_done.html
<!--Password reset sent-->
<div class="container p-5">
    <h2 class="font-weight-bold mt-3">Password reset sent</h2>
      <hr>
      <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
</div>

templates/project/post/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
	<title>Register Page</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins" style="background: #00203fff;">
        <div class="wrapper wrapper--w780">
            <div class="card card-3">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title">Registration Info</h2>
                    <form method="POST" action="user_register">
						{% csrf_token %}
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="Name" name="name" required="">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="text" placeholder="Username" name="username" required="">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="email" placeholder="Email" name="email" required="">
                        </div>
                        <div class="input-group">
                            <input class="input--style-3" type="password" placeholder="Password" name="pswd" required="">
                        </div>
						<div class="input-group">
                            <input class="input--style-3" type="password" placeholder="confirm password" name="cpswd" required="">
                        </div>
                        <div class="p-t-10">
                            <button class="btn btn--pill btn--green" type="submit">Submit</button>
                        </div>
						<p class="mt-3" style="color: #00203fff;">Already have an accout? <a href="{% url 'project:user_login' %}">Login</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

templates/project/post/reset_password_complete.html
<div>
    <h1>Password Reset Complete</h1>
    <p>Your Password is set now <a href="#">Login</a> with your new password</p>
</div>

templates/project/post/reset_password_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
	<title>Login Page</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    
    <div class="page-wrapper bg-gra-01 p-t-180 p-b-100 font-poppins" style="background: #00203fff;">
        <div class="wrapper wrapper--w780">
            <div class="card card-3" style="background: #fff;">
                <div class="card-heading"></div>
                <div class="card-body">
                    <h2 class="title">Reset Password</h2>
                    {% if validlink %}
                            <form method="post" action="user_login" id="form">
                                {% csrf_token %}
                                        <div class="input-group">
                                            <input class="input--style-3" id = 'password' type="password" placeholder="Password" name="pswd" required="">
                                        </div>
                                        <div class="input-group">
                                            <input class="input--style-3" id='password' type="password" placeholder="Confirm Password" name="cpswd" required="">
                                        </div>
                                <div class="p-t-10">
                                    <button class="btn btn--pill btn--green" id='submit' type="submit">Change Password</button>
                                </div>
                            </form>
                    {% else %}
                    <p>The Reset Password Link is Invalid or have expired.Kindly request another password reset link</p>
                    {% endif %}
                        </div>
                    </div>
                </div>
            </div>

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->

templates/project/post/reset_password_email.html
Someone asked for password reset of this email {{ email }} follow this link below:

{{ protocol }}://{{ domain }}{% url "forgot_password_confirm" uidb64=uid token=token %}
Your Username: {{ user.get_username }}